### ISSUE TITLE
功能请求：添加libjxl

### ISSUE THREAD

**Issue by eko5624** [nyfair/mpv-win64#12]
MPV最近更新加入了JEPG XL截屏支持，可以考虑把libjxl也编译进去了。

**Comment by nyfair** [comment]
没兴趣，libjxl体积远大于mpv，甚至大于不含依赖的ffmpeg

**Comment by eko5624** [comment]
体积大吗，好像不大呀。shinchiro编译出来带libjxl的版本也没比之前的大多少。
