### ISSUE TITLE
Can add option for x86-64-v3 target?

### ISSUE THREAD

**Issue by eko5624** [nyfair/mpv-win64#16]
今天看到shinchiro编译的版本里增加了x86-64-v3的支持，我们的编译版本支持吗。

The x86-64-v3 level enables AVX, AVX2, BMI2, MOVBE, XSAVE and other modern instructions which benefit modern cpu.

**Comment by nyfair** [comment]
v3并不modern，根本就是中古cpu，甚至v4都已经是6年前的老黄历了
我的优化策略本来就比他激进，没理由去用他的参数

**Comment by eko5624** [comment]
好滴，明白啦，谢谢解惑。

**Comment by nyfair** [comment]
各种自定义的优化参数可以看这两篇文章
https://wiki.gentoo.org/wiki/Safe_CFLAGS
https://wiki.gentoo.org/wiki/GCC_optimization
