### ISSUE TITLE
建议：增加libdovi的编译

### ISSUE THREAD

**Issue by eko5624** [nyfair/mpv-win64#18]
libplacebo加入了对libdovi的支持，希望可以考虑也编译进去。

**Comment by nyfair** [comment]
谢谢，顺便提下你搬shinchiro的cmake脚本搬错了，shell和cmake command并不兼容，所以那些rust优化参数都没有生效
要么全写在一行要么前面加export

**Comment by eko5624** [comment]
谢谢提醒。问题是我不知道怎么用rust的toolchain编译生成.a文件而不是.lib文件。所以想看看你是怎么编译的

**Comment by nyfair** [comment]
话说我粗看了下，这次是直接把之前的映射方案全盘删掉了，然而无论是mpv还是libplacebo这块都是haasn一个人在单干效率也不高
虽然以前的方案的确问题多多，但是这么迈步子现在很多行为并不对吧

**Comment by eko5624** [comment]
> 

我用rust msvc toolchain可以成功编译libdovi，但最终编译mpv时会失败。编译日志如下：
https://github.com/eko5624/mpv-win64/actions/runs/4277623593/jobs/7446965192

**Comment by eko5624** [comment]
改用rust gnu工具链编译成功了，步骤如下：

用rustup安装gnu工具链：stable-x86_64-pc-windows-gnu。然后下载编译好的cargo-c-windows-gnu.zip解压放到C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-gnu\bin目录，这样会节省不少时间。

**Comment by nyfair** [comment]
set是windows cmd的命令，你shell下得用export

**Comment by nyfair** [comment]
谢谢，就用你的方案吧，编译cargo-c太浪费时间了，最后生成的导入表还是错的
