### ISSUE TITLE
fork master do batch-bleeding_edge-weekly fail

### ISSUE THREAD

**Issue by pinximei** [nyfair/mpv-win64#19]
能帮我看下，为啥我fork master分支后，我执行batch-bleeding_edge-weekly失败了，
错误：
configure: error: in `/d/a/mpv-win64/mpv-win64/lcms2-dev/src/lcms2-2.15':
configure: error: C compiler cannot create executables

**Comment by nyfair** [comment]
不知道你第一次是怎么跑的，最初的记录被你清掉了
action/cache
Received 30 of 30 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (30 B)
但是这个存放编译链的缓存肯定是空的

先把这个cache删了重新跑一遍toolchain

**Comment by pinximei** [comment]
按照上面流程能正常编译了
