### ISSUE TITLE
mpv.exe --version 命令没有反应

### ISSUE THREAD

**Issue by CCCAUCHY** [nyfair/mpv-win64#21]

**Comment by nyfair** [comment]
Cannot reproduce
![image](https://github.com/nyfair/mpv-win64/assets/1343411/bf027df5-5e60-4485-8f1a-708d841e76d1)

**Comment by CCCAUCHY** [comment]
> Cannot reproduce 

Windows Terminal
![image](https://github.com/nyfair/mpv-win64/assets/55306290/a12ffba8-683d-4e33-aa3f-e1dd9154b625)

**Comment by nyfair** [comment]
mpv.exe doesn't use the Windows Console API, you should call mpv.com instead.
I don't bundle mpv.com in my release.
[mpv.com.zip](https://github.com/nyfair/mpv-win64/files/13510077/mpv.com.zip)
