### ISSUE TITLE
workflow错误

### ISSUE THREAD

**Issue by eko5624** [nyfair/mpv-win64#3]
下面几组代码模块的加入。fork到自己的repo，第一次执行toolchain.yml和batch-bleeding_edge-weekly.yml时，编译不通过。 因为第一次执行会提示找不到相应assets，然后结束工作流程。看是否需要改进下。

name: Delete
      uses: mknejp/delete-release-assets@v1

**Comment by nyfair** [comment]
第一次就先手动去掉这些呗
我是懒得删改才加上的

**Comment by eko5624** [comment]
知道啦
