### ISSUE TITLE
autoupdate问题疑惑

### ISSUE THREAD

**Issue by eko5624** [nyfair/mpv-win64#5]
真心求教个问题。因为我不是学编程的，好多东西搞不明白。有个问题困扰了我好多天了。google出的答案也是一知半解。您如果能帮我解惑就太感谢了。

我仓库里这个autoupdate老是运行失败是什么原因。之前组件版本有更新还能自动更新到仓库，现在不行了。比如ffmpeg版本号已经到4.4.1了，还有其他的组件版本即使有版本更新，也不能同步到build - weekly.yml里面。我已经在个人账号里设置了PAT。然后在mpv-win64仓库里也设置了仓库secret。是不是autoupdate.py抄您的没抄对，还是其他哪里的问题？您能帮我看看吗，谢谢。

**Comment by nyfair** [comment]
应该是我没写好，git什么也没更新时commit会报错的，得加个判断

**Comment by eko5624** [comment]
多谢指导，问题解决了。autoupdate.py我没写对，重新改了一下，可以更新到yml了。
