### ISSUE TITLE
mpv compile failed 

### ISSUE THREAD

**Issue by eko5624** [nyfair/mpv-win64#7]
Maybe it's [this](https://github.com/mirror/mingw-w64/commit/09def642bf5e8a78195791257ff53fd920c549d1) change . MPV team's this [PR](https://github.com/mpv-player/mpv/pull/9667) will fix it soon.

So I rollback to mcf_20211207_11.2.1_x64-ucrt temporarily.

**Comment by nyfair** [comment]
Thanks, latest [patch](https://github.com/mirror/mingw-w64/commits/master) from mingw should fix this
