### ISSUE TITLE
mcfgthread重构问题

### ISSUE THREAD

**Issue by eko5624** [nyfair/mpv-win64#9]
lhmouse大佬重构mcfgthread了，所以我们也需要修改toolchain以适应上游变化。你看看怎么改哈。

**Comment by nyfair** [comment]
折腾编译器意义太小了，先拿上个版本凑活下等它结构稳定吧

eko5624 ***@***.***> 于 2022年4月10日周日 16:33写道：

**Comment by nyfair** [comment]
嘛，至少明面上除了dll换了名字也没啥需要大改的
